name: build-scrapper

on:
        push:
                paths:
                        - 'src/**'

jobs:

        build:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout
                          uses: actions/checkout@v3

                        - name: Setup JDK
                          uses: actions/setup-java@v3
                          with:
                                  distribution: 'temurin'
                                  java-version: '17'
                                  cache: maven

                        - name: Maven package scrapper
                          run: mvn package -pl TnTasks_MediumLvl -am


